export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SCHOOL_SCOPE_MISSING: 'SCHOOL_SCOPE_MISSING',
  RATE_LIMITED: 'RATE_LIMITED',
  // Platform-plane errors
  IP_NOT_ALLOWED: 'IP_NOT_ALLOWED',
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_INVALID: 'MFA_INVALID',
  OWNER_ONLY: 'OWNER_ONLY',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
